name: Pull Request Tests

on:
  pull_request:
    branches:
      - dev
      - testing

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            **/.cache
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Generate Prisma Client
        run: yarn prisma generate

      - name: Apply Prisma Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: yarn prisma migrate deploy

      - name: Lint code
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: yarn lint

      - name: Check TypeScript types
        run: yarn typecheck

      - name: Build project
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: yarn build
